<?php
/**
 * @file
 * laliste_homepage_content_type.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function laliste_homepage_content_type_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance:
  // 'node-homepage_featured_image-field_slideshow_image'
  $field_instances['node-homepage_featured_image-field_slideshow_image'] = array(
    'bundle' => 'homepage_featured_image',
    'deleted' => 0,
    'description' => 'Select images to be used for homepage slideshow',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => 'full-width_slider_image',
        ),
        'type' => 'image',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'fences_wrapper' => 'div',
    'field_name' => 'field_slideshow_image',
    'label' => 'Slideshow image',
    'required' => 0,
    'settings' => array(
      'alt_field' => 0,
      'default_image' => 0,
      'entity_translation_sync' => FALSE,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'media',
      'settings' => array(
        'allowed_schemes' => array(
          'public' => 'public',
        ),
        'allowed_types' => array(
          'audio' => 0,
          'document' => 0,
          'image' => 'image',
          'video' => 0,
        ),
        'browser_plugins' => array(
          'media_default--media_browser_1' => 0,
          'media_default--media_browser_my_files' => 0,
          'upload' => 0,
        ),
      ),
      'type' => 'media_generic',
      'weight' => 1,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Select images to be used for homepage slideshow');
  t('Slideshow image');

  return $field_instances;
}
