<?php

function facetapi_select_facet_form($form, &$form_state, $variables, $count = 0) {
  $name = 'facetapi_select_facet_form_' . $count;

  // Add link to deactive widget if currently active
  if (!empty($variables['active_items'])) {
    $form['deactivate_links'] = array(
      '#theme' => 'item_list',
      '#items' => $variables['active_items']
    );
  }

  if (!empty($variables['options'])) {
    $form['facets'] = array(
      '#type' => 'select',
      '#id' => $name,
      '#name' => $name,
      '#default_value' => '',
      '#options' => $variables['options'],
      '#attributes' => array(
        'class' => array('facetapi-select'),
      ),
      '#attached' => array(
        'js' => array(
          drupal_get_path('module', 'facetapi_select') .'/js/facetapi_select.js',
        ),
      ),
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#attributes' => array('class' => array('facetapi-select-submit')),
      '#value' => t('Submit'),
    );
  }

  if (!empty($variables['default_option_label'])) {
    $form['facets']['#empty_option'] = $variables['default_option_label'];
  }

  return $form;
}

/**
 * Submit function for facetapi_select_form().
 */
function facetapi_select_facet_form_submit($form, &$form_state) {
  preg_match('/^\/(.*)\?(.*)/', $form_state['values']['facets'], $filters);
  drupal_goto($filters[1], $query = $filters[2]);
}

/**
 * Implements hook_facetapi_widgets().
 */
function facetapi_select_facetapi_widgets() {
  return array(
    'facetapi_select_dropdowns' => array(
      'handler' => array(
        'label' => t('Select Field (Dropdowns)'),
        'class' => 'FacetapiSelectDropdowns',
        'query types' => array('term', 'date'),
      ),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function facetapi_select_theme() {
  return array(
    'facetapi_select_select_option' => array(
      'variables' => array(
        'facet_text' => NULL,
        'facet_count' => 0,
        'show_count' => TRUE,
      ),
    ),
  );
}

/**
 * Theme an individual select option.
 */
function theme_facetapi_select_select_option($variables) {
  $output = $variables['facet_text'];

  if ($variables['show_count']) {
    $output .= ' (' . $variables['facet_count'] . ')';
  }

  return $output;
}
