<?php

/**
 * Implements hook_block_info().
 */
function laliste_homepage_block_info() {
  $blocks = array();
  $blocks['home_search'] = array(
    'info' => t('Home Search Block'),
  );
  $blocks['home_highlight'] = array(
    'info' => t('Home Highlight Block'),
  );
  $blocks['home_methodology'] = array(
    'info' => t('Home Methodology Block'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function laliste_homepage_block_view($delta='') {
  $block = array();

  switch($delta) {
    case 'home_search':
      $block = generate_home_search_block();
    break;
    case 'home_highlight':
      $block = generate_home_highlight_block();
    break;
    case 'home_methodology':
      $block = generate_home_methodology_block();
  }

  return $block;
}

function generate_home_methodology_block(){
  $block = array();
  $block['subject'] = '';
  $block['content'] = "
  <div class='method-container'>
    <div class='method-main-title'>".t('Our Method')."</div>
    <div class='method-content-block'>".t('While it was until recently reserved for an elite, global gastronomy is changing fast. All around the world, it has entered daily life through entertainment and images, while new culinary cultures are emerging constantly, happily renewing the codes of cooking, the world’s “oldest art”')."
    </div>
    <div class='method-title method-experts'>".t('Our Experts')."</div>
    <div class='method-content-block'>
      <img src='".base_path().path_to_theme().'/img/our-experts.png'."' alt='Experts of LA LISTE'>
    </div>
    <div class='method-title method-algorithm'>".t('Our Algorithm')."</div>
    <div class='method-content-block'>
      <img src='".base_path().path_to_theme().'/img/our-algorithm.png'."' alt='Ciacco Algorithm of LA LISTE'>
    </div>
    <div class='method-title method-liste'>".t('Our Liste')."</div>
    <div class='method-content-block'>
      <img src='".base_path().path_to_theme().'/img/our-liste.png'."' alt='La Liste of a 1000 Remarkable Restaurants'>
    </div>
  </div>
  <div class='method-link'><a href='our-method'>".t('Discover How we did it!')."</a></div>";
  return $block;
}

function generate_home_highlight_block() {
  global $language;
  $lang_name = $language->language ;
  $block = array();
  $block['subject'] = '';
  if($lang_name == 'en') {
    $block['content'] = "
    <div class='highlight-container'>
      <div class='highlight-title'>".t('Welcome To Your Global Table !')."</div>
      <div class='highlight-content-container'>
        <div class='highlight-content-column'><p>".check_plain(variable_get('highlight_left_block_en', "Culinary Connoisseurs Of All Countries and Creeds, your search for exceptional experiences around the world starts at LA LISTE. Food is a global obsession. Every year, experts and amateurs create and publish millions of restaurant reviews. LA LISTE uses score averaging and semantic analysis to keep up,"))."</p>
        </div>
        <div class='highlight-content-column'><p>".check_plain(variable_get('highlight_center_block_en', "searching in 200+ food guides, review sites, gourmet blogs, social media, and major national and local publications in 48 countries. The result is LA LISTE: 1,000 Remarkable Restaurants highlighting most-loved food destinations worldwide. At the heart of our rankings is an algorithm that quantifies"))."</p>
        </div>
        <div class='highlight-content-column'><p>".check_plain(variable_get('highlight_right_block_en', " the epicurian pleasure experienced by critics and diners like you - because &laquo; gastronomy is the art of using food to create happiness &raquo;. We believe that numbers speak for themselves, and we are here to translate them into a language for gourmands everywhere."))."</p>
        </div>
    </div>";
  }
  elseif($lang_name == 'fr') {
    $block['content'] = "
    <div class='highlight-container'>
      <div class='highlight-title'>".t('Bienvenue sur la planète gastronomie !')."</div>
      <div class='highlight-content-container'>
        <div class='highlight-content-column'><p>".check_plain(variable_get('highlight_left_block_fr', "Voyageurs, touristes, gourmets, vous qui cherchez des avis fiables sur des restaurants sous toutes les latitudes, consultez LA LISTE ! Vous y trouvez &laquo; 1000 restaurants d'exception &raquo; classés par les guides nationaux de 48 pays. Les critères retenus portent"))."</p>
        </div>
        <div class='highlight-content-column'><p>".check_plain(variable_get('highlight_center_block_fr', " sur la cuisine, le cadre, le service, l'accueil et la cave, et aussi par les notes des sites participatifs et des principaux grands média. L'algorithme qui intègre ces données reflète le plaisir éprouvé par les dégustateurs, inspecteurs de guides ou particuliers."))."</p>
        </div>
        <div class='highlight-content-column'><p>".check_plain(variable_get('highlight_right_block_fr', "<em>&laquo; La gastronomie est l'art d'utiliser la nourriture pour créer du bonheur &raquo;</em> selon Théodore Zeldin, qui s'applique à l'art culinaire de tous les pays, selon les usages culturels dont chaque cuisinier est l'interprète, quel que soit le produit qu'il transforme."))."</p>
        </div>
    </div>";
  }
  return $block;
}

/**
 * Custom function to assemble renderable array for block content.
 * Returns a renderable array with the block content.
 * @return
 *   returns a renderable array of block content.
 */
function generate_home_search_block() {
  $block = array();

  // Capture the image file path and form into HTML with attributes
  $image_file = file_load(variable_get('block_image_fid', ''));
  $image_path = '';

  if (isset($image_file->uri)) {
    $image_path = $image_file->uri;
  }

  $image = theme_image(array(
    'path' => ($image_path),
    'alt' => t('Image description here.'),
    'title' => t('This is our block image.'),
    'attributes' => array('class' => 'class_name'),
  ));

  // Capture WYSIWYG text from the variable
  $text = variable_get('text_variable', '');

  // Block output in HTML with div wrapper
  $block = array(
    'image' => array(
      '#prefix' => '',
      '#type' => 'markup',
      '#markup' => $image,
    ),
    'message' => array(
      '#type' => 'markup',
      '#markup' => $text,
      '#suffix' => '',
    ),
  );

  return $block;
}

/*
** Highlight Block Admin Settings Page
 */

/**
 * Implements hook_menu().
 */
function laliste_homepage_menu() {
  $items['admin/structure/homepage'] = array(
    'title' => 'Homepage content edit',
    'description' => 'Edit content for the homepage.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('laliste_homepage_settings'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Menu callback: displays the laliste homepage module settings page.
 *
 * @ingroup forms
 *
 * @see laliste_homepage_settings_validate()
 * @see laliste_homepage_settings_submit()
 */
function laliste_homepage_settings($form, &$form_state) {

  // english language
  $form['highlight_left_block_en'] = array(
    '#type' => 'textarea',
    '#title' => t('Highlight left block - english'),
    '#description' => t('Shows the content into the left block of the highlight section.'),
    '#default_value' => variable_get('highlight_left_block_en', "Culinary Connoisseurs Of All Countries and Creeds, your search for exceptional experiences around the world starts at LA LISTE. Food is a global obsession. Every year, experts and amateurs create and publish millions of restaurant reviews. LA LISTE uses score averaging and semantic analysis to keep up,"),
  );

  $form['highlight_center_block_en'] = array(
    '#type' => 'textarea',
    '#title' => t('Highlight center block - english'),
    '#description' => t('Shows the content into the center block of the highlight section.'),
    '#default_value' => variable_get('highlight_center_block_en', "searching in 200+ food guides, review sites, gourmet blogs, social media, and major national and local publications in 48 countries. The result is LA LISTE: 1,000 Remarkable Restaurants highlighting most-loved food destinations worldwide. At the heart of our rankings is an algorithm that quantifies"),
  );

  $form['highlight_right_block_en'] = array(
    '#type' => 'textarea',
    '#title' => t('Highlight right block - english'),
    '#description' => t('Shows the content into the right block of the highlight section.'),
    '#default_value' => variable_get('highlight_right_block_en', " the epicurian pleasure experienced by critics and diners like you - because &laquo; gastronomy is the art of using food to create happiness &raquo;. We believe that numbers speak for themselves, and we are here to translate them into a language for gourmands everywhere."),
  );

  // french language
  $form['highlight_left_block_fr'] = array(
    '#type' => 'textarea',
    '#title' => t('Highlight left block - french'),
    '#description' => t('Shows the content into the left block of the highlight section.'),
    '#default_value' => variable_get('highlight_left_block_fr', "Voyageurs, touristes, gourmets, vous qui cherchez des avis fiables sur des restaurants sous toutes les latitudes, consultez LA LISTE ! Vous y trouvez &laquo; 1000 restaurants d'exception &raquo; classés par les guides nationaux de 48 pays. Les critères retenus portent"),
  );

  $form['highlight_center_block_fr'] = array(
    '#type' => 'textarea',
    '#title' => t('Highlight center block - french'),
    '#description' => t('Shows the content into the center block of the highlight section.'),
    '#default_value' => variable_get('highlight_center_block_fr', " sur la cuisine, le cadre, le service, l'accueil et la cave, et aussi par les notes des sites participatifs et des principaux grands média. L'algorithme qui intègre ces données reflète le plaisir éprouvé par les dégustateurs, inspecteurs de guides ou particuliers."),
  );

  $form['highlight_right_block_fr'] = array(
    '#type' => 'textarea',
    '#title' => t('Highlight right block - french'),
    '#description' => t('Shows the content into the right block of the highlight section.'),
    '#default_value' => variable_get('highlight_right_block_fr', "<em>&laquo; La gastronomie est l'art d'utiliser la nourriture pour créer du bonheur &raquo;</em> selon Théodore Zeldin, qui s'applique à l'art culinaire de tous les pays, selon les usages culturels dont chaque cuisinier est l'interprète, quel que soit le produit qu'il transforme."),
  );

  $form['#validate'][] = 'laliste_homepage_settings_validate';
  $form['#submit'][] = 'laliste_homepage_settings_submit';

  // Use system_settings_form() to automate saving configuration variables.
  return system_settings_form($form);
}

/**
 * Form validation handler for search_admin_settings().
 */
function laliste_homepage_settings_validate($form, &$form_state) {
  // Check whether we selected a valid default.
  /*
  if ($form_state['triggering_element']['#value'] != t('Reset to defaults')) {
    $new_modules = array_filter($form_state['values']['search_active_modules']);
    $default = $form_state['values']['search_default_module'];
    if (!in_array($default, $new_modules, TRUE)) {
      form_set_error('search_default_module', t('Your default search module is not selected as an active module.'));
    }
  }*/
}

/**
 * Form submission handler for search_admin_settings().
 */
function laliste_homepage_settings_submit($form, &$form_state) {

  //$current_modules = variable_get('search_active_modules', array('node', 'user'));
  // Check whether we are resetting the values.
  //if ($form_state['triggering_element']['#value'] == t('Reset to defaults'))

    //drupal_set_message(t('The active search modules have been changed.'));
    //variable_set('menu_rebuild_needed', TRUE);
}

